### ISSUE TITLE
[GithubWebhooks] No signature on URL

### ISSUE THREAD

**Issue by HarHarLinks** [matrix-org/matrix-hookshot#183]
```
Jan 23 16:52:58 matrix-hookshot[484998]: ERROR 15:52:58:305 [GithubWebhooks] No signature on URL. Rejecting
Jan 23 16:52:58 matrix-hookshot[484998]: Error: Invalid signature.
Jan 23 16:52:58 matrix-hookshot[484998]:     at Webhooks.verifyRequest (/bin/matrix-hookshot/Webhooks.js:275:15)
Jan 23 16:52:58 matrix-hookshot[484998]:     at /bin/matrix-hookshot/node_modules/body-parser/lib/read.js:104:9
Jan 23 16:52:58 matrix-hookshot[484998]:     at invokeCallback (/bin/matrix-hookshot/node_modules/raw-body/index.js:224:16)
Jan 23 16:52:58 matrix-hookshot[484998]:     at done (/bin/matrix-hookshot/node_modules/raw-body/index.js:213:7)
Jan 23 16:52:58 matrix-hookshot[484998]:     at IncomingMessage.onEnd (/bin/matrix-hookshot/node_modules/raw-body/index.js:273:7)
Jan 23 16:52:58 matrix-hookshot[484998]:     at IncomingMessage.emit (node:events:402:35)
Jan 23 16:52:58 matrix-hookshot[484998]:     at endReadableNT (node:internal/streams/readable:1343:12)
Jan 23 16:52:58 matrix-hookshot[484998]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
This happens to me when the github app tries to deliver a webhook, e.g. when installing the app to a repo. The webhook URL is the root path of the webhook listener, which is reverse proxied to `/hookshot/webhooks/` by nginx. Response code according to github is `400 Bad Request`.

**Comment by Half-Shot** [comment]
If I recall correctly, that's when it's not happy about the payload / headers in the webhook. I'll do some digging.

**Comment by sai-blocktrace** [comment]
Did you fix?

**Comment by HarHarLinks** [comment]
This issue disappeared for me.

**Comment by sai-blocktrace** [comment]
What do you mean by that?
