### ISSUE TITLE
Error when connecting to GitHub

### ISSUE THREAD

**Issue by hwittenborn** [matrix-org/matrix-hookshot#365]
**Describe the bug**
The bot keeps exiting with a 404 when connecting to `https://github.com/api/v3/app`.

**Server Logs**
```jsonnet
INFO 20:24:48:362 [Bridge] Initialising memory storage
INFO 20:24:48:366 [Bridge] Starting up
INFO 20:24:48:366 [Bridge] Connecting to homeserver and fetching joined rooms..
INFO 20:24:48:414 [Config] Prefilling room membership for permissions for 0 rooms
ERROR 20:24:48:469 [App] BridgeApp encountered an error and has stopped: RequestError [HttpError]: Not Found
    at /bin/matrix-hookshot/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async hook (/bin/matrix-hookshot/node_modules/@octokit/auth-app/dist-node/index.js:409:18)
    at async GithubInstance.start (/bin/matrix-hookshot/Github/GithubInstance.js:93:28)
    at async Bridge.start (/bin/matrix-hookshot/Bridge.js:86:13)
    at async start (/bin/matrix-hookshot/App/BridgeApp.js:38:5) {
  status: 404,
  response: {
    url: 'https://github.com/api/v3/app',
    status: 404,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
      'content-type': 'text/plain; charset=utf-8',
      date: 'Sat, 28 May 2022 20:24:48 GMT',
      'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
      'permissions-policy': 'interest-cohort=()',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'set-cookie': 'logged_in=no; domain=.github.com; path=/; expires=Sun, 28 May 2023 20:24:48 GMT; secure; HttpOnly; SameSite=Lax',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-request-id': '9CB4:0AAE:5ECE29:AF2E67:62928510',
      'x-xss-protection': '0'
    },
    data: 'Not Found'
  },
  request: {
    method: 'GET',
    url: 'https://github.com/api/v3/app',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'matrix-hookshot/1.7.1 (+https://github.com/matrix-org/matrix-hookshot) octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/16.15.0 (linux; x64)',
      authorization: 'bearer [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by tadzik** [comment]
Thanks, this is a recent regression and will be fixed soon. You can try the patch above in the meantime, if you have that option.
