### ISSUE TITLE
Can't give permissions to MXID

### ISSUE THREAD

**Issue by FarisZR** [matrix-org/matrix-hookshot#452]
**Describe the bug**
When I set the Admin permissions to a specif MXID, the bridges crashes.

**To Reproduce**
1. Edit config
2. Give admin permissions to a specific MXID

**Expected behavior**
It should just work

**Logs**

```
matrix-hookshot  | }
matrix-hookshot  | ERROR 21:24:43:080 [App] Got SIGTERM
matrix-hookshot  | INFO 21:24:43:080 [ListenerService] Stopping all listeners
matrix-hookshot  | ERROR 21:24:54:555 [App] BridgeApp encountered an error and has stopped: YAMLSemanticError: Plain value cannot start with reserved character @
matrix-hookshot  |     at PlainValue.get strValue [as strValue] (/bin/matrix-hookshot/node_modules/yaml/dist/PlainValue-ec8e588e.js:773:27)
matrix-hookshot  |     at resolveString (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1328:20)
matrix-hookshot  |     at resolveNodeValue (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1590:17)
matrix-hookshot  |     at resolveNode (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
matrix-hookshot  |     at resolveBlockMapItems (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1823:38)
matrix-hookshot  |     at Object.resolveMap [as resolve] (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1658:79)
matrix-hookshot  |     at resolveByTagName (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1430:25)
matrix-hookshot  |     at resolveTag (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1460:17)
matrix-hookshot  |     at resolveNodeValue (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1581:23)
matrix-hookshot  |     at resolveNode (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15)
matrix-hookshot  |     at resolveBlockSeqItems (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:2012:20)
matrix-hookshot  |     at Object.resolveSeq [as resolve] (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1975:79)
matrix-hookshot  |     at resolveByTagName (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1430:25)
matrix-hookshot  |     at resolveTag (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1460:17)
matrix-hookshot  |     at resolveNodeValue (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1581:23)
matrix-hookshot  |     at resolveNode (/bin/matrix-hookshot/node_modules/yaml/dist/resolveSeq-d03cb037.js:1629:15) {
matrix-hookshot  |   source: PlainValue {
matrix-hookshot  |     error: null,
matrix-hookshot  |     range: Range { start: 3475, end: 3491 },
matrix-hookshot  |     valueRange: Range { start: 3475, end: 3491 },
matrix-hookshot  |     props: [],
matrix-hookshot  |     type: 'PLAIN',
matrix-hookshot  |     value: null,
matrix-hookshot  |     resolved: Scalar { value: '@admin:domain.com', range: [Array], type: 'PLAIN' }
matrix-hookshot  |   }
matrix-hookshot  | }

```

**Config**
```
permissions:
  # (Optional) Permissions for using the bridge. See docs/setup.md#permissions for help
  #
  - actor: @admin:domain.com
    services:
      - service: "*"
        level: admin
```

**Additional context**
this should work according to the docs.
https://matrix-org.github.io/matrix-hookshot/latest/setup.html#permissions

**Comment by Half-Shot** [comment]
It might want you to wrap it in quotes?

**Comment by FarisZR** [comment]
seems to have fixed it, but that isn't mentioned in the docs.

**Comment by Half-Shot** [comment]
I'll update the docs with some info :+1: , thanks for the report.
