### ISSUE TITLE
Support bridging multiple jira projects in the same room

### ISSUE THREAD

**Issue by gaelgatelement** [matrix-org/matrix-hookshot#533]
At the moment, running the following commands multiple times in the same room  : 

`!hookshot jira project <project>`

Results in : 

```
WARN 08:09:44:493 [CommandConnection] Failed to handle command: Error: Cannot support multiple connections of the same type yet
    at Function.provisionConnection (/bin/matrix-hookshot/Connections/JiraProject.js:74:19)
    at SetupConnection.onJiraProject (/bin/matrix-hookshot/Connections/SetupConnection.js:125:52)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleCommand (/bin/matrix-hookshot/BotCommands.js:105:32)
    at async SetupConnection.onMessageEvent (/bin/matrix-hookshot/Connections/CommandConnection.js:41:31)
    at async Bridge.onRoomMessage (/bin/matrix-hookshot/Bridge.js:606:21)
```

**Comment by Half-Shot** [comment]
@AndrewFerr I think we talked about this one?

**Comment by AndrewFerr** [comment]
That we did.  This may very well already work, aside from this defensive error.  I'll remove it and see what happens.
