### ISSUE TITLE
Generic Webhooks not working anymore with 2.6.0

### ISSUE THREAD

**Issue by Kidswiss** [matrix-org/matrix-hookshot#625]
Hi

I've upgraded to 2.6.0 and found that generic webhooks aren't working anymore for me.

Here's the relevant log:
```
INFO 10:26:12:592 [GenericHookConnection] onGenericHook !giPbCwyFjMCwVsXeJt:matrix.secret.ch d2127879-c8be-4438-93d0-cb90088fb8ad
ERROR 10:26:12:609 [MatrixHttpClient] (REQ-64) {
  errcode: 'M_FORBIDDEN',
  error: '@hookshot_user:matrix.secret.ch is already in the room.'
}
WARN 10:26:12:609 [Bridge] Failed to handle generic webhook MatrixError: M_FORBIDDEN: @hookshot_user:matrix.secret.ch is already in the room.
    at doHttpRequest (/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/http.js:95:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MatrixClient.descriptor.value (/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
    at async MatrixClient.descriptor.value (/bin/matrix-hookshot/node_modules/matrix-bot-sdk/lib/metrics/decorators.js:19:32)
    at async GenericHookConnection.onGenericHook (/bin/matrix-hookshot/Connections/GenericHook.js:304:13)
    at async /bin/matrix-hookshot/Bridge.js:367:38
    at async Promise.all (index 0)
    at async LocalMQ.<anonymous> (/bin/matrix-hookshot/Bridge.js:358:13) {
  body: {
    errcode: 'M_FORBIDDEN',
    error: '@hookshot_user:matrix.secret.ch is already in the room.'
  },
  statusCode: 403,
  errcode: 'M_FORBIDDEN',
  error: '@hookshot_user:matrix.secret.ch is already in the room.',
  retryAfterMs: undefined
}
```

When removing the `@hookshot_user:matrix.secret.ch` user from the room, then exactly one message works and then it breaks again with above errors. Looks like hookshot tries to add the bot user on each request and fails because it's already there.

Downgrading back to 2.5.0 and it works as it's supposed to.

**Comment by Half-Shot** [comment]
Thanks for the report, we're looking into it.
