### ISSUE TITLE
[Webhooks] No signature on URL. Rejecting / Error: Invalid signature

### ISSUE THREAD

**Issue by tuc-ok** [matrix-org/matrix-hookshot#762]
Is it a bug or a configuration failure that matrix-hookshot (v4.0.0) rejects POST request with this error message?

2023-05-20T07:58:28.465955610Z ERROR 07:58:28:465 [Webhooks] No signature on URL. Rejecting
2023-05-20T07:58:28.468245523Z Error: Invalid signature.
2023-05-20T07:58:28.468286896Z     at Webhooks.verifyRequest (/bin/matrix-hookshot/Webhooks.js:332:15)
2023-05-20T07:58:28.468297706Z     at /bin/matrix-hookshot/node_modules/express/node_modules/body-parser/lib/read.js:104:9
2023-05-20T07:58:28.468306406Z     at invokeCallback (/bin/matrix-hookshot/node_modules/express/node_modules/raw-body/index.js:224:16)
2023-05-20T07:58:28.468314124Z     at done (/bin/matrix-hookshot/node_modules/express/node_modules/raw-body/index.js:213:7)
2023-05-20T07:58:28.468321338Z     at IncomingMessage.onEnd (/bin/matrix-hookshot/node_modules/express/node_modules/raw-body/index.js:273:7)
2023-05-20T07:58:28.468328887Z     at IncomingMessage.emit (node:events:513:28)
2023-05-20T07:58:28.468336135Z     at IncomingMessage.emit (node:domain:489:12)
2023-05-20T07:58:28.468343407Z     at endReadableNT (node:internal/streams/readable:1359:12)
2023-05-20T07:58:28.468351082Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Half-Shot** [comment]
Well, it's saying the request it received didn't pass a signature check which means a secret could be wrong in the hookshot config or the remote service config. Was this GitHub/GitLab?

**Comment by tuc-ok** [comment]
I think we can close this case.

It was a general webhook. I am afraid that I tried to send the webhook to a wrong URL. After I have created an new webhook connection it worked as expected. Thank you very much for your help!
