### ISSUE TITLE
[Error]:  signature does not match event payload and secret

### ISSUE THREAD

**Issue by mike-pisman** [matrix-org/matrix-hookshot#842]
Hi, just set up hookshot, tried to send 2 events but got errors.

```
ERROR 00:34:46:245 [Webhooks] Failed handle GitHubEvent: AggregateError: 
    Error: [@octokit/webhooks] signature does not match event payload and secret
        at verifyAndReceive (/usr/bin/matrix-hookshot/node_modules/@octokit/webhooks/dist-node/index.js:259:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR 00:37:50:204 [Webhooks] Failed handle GitHubEvent: AggregateError: 
    Error: [@octokit/webhooks] signature does not match event payload and secret
        at verifyAndReceive (/usr/bin/matrix-hookshot/node_modules/@octokit/webhooks/dist-node/index.js:259:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Half-Shot** [comment]
Sorry, this took a long time to get back to. So this error is because the `github.webhook.secret` in your config does not match what GitHub has configured in the App settings. Each request from GitHub is signed to prevent forgery, so it will error if there is a mismatch.
