### ISSUE TITLE
Hookshot crash when activating back notification

### ISSUE THREAD

**Issue by RoiArthurB** [matrix-org/matrix-hookshot#965]
From a private chat with hookshot, if I send two times `github notifications toggle` in a row, the bot will crash :

```
Jul 16 11:26:15 DietPi matrix-hookshot[798238]: WARN 04:26:15:367 [Config] You have not configured any permissions for the bridge, which by default means all users on roiarthurb.xyz have admin levels of control. Please adjust your config.
Jul 16 11:26:15 DietPi matrix-hookshot[798238]: INFO 04:26:15:401 [ListenerService] Listening on http://0.0.0.0:9000 for webhooks
Jul 16 11:26:15 DietPi matrix-hookshot[798238]: INFO 04:26:15:403 [ListenerService] Listening on http://0.0.0.0:9003 for widgets
Jul 16 11:26:17 DietPi matrix-hookshot[798238]: ERROR 04:26:17:177 [Bridge] Failed to set up admin room !XXX:YY.ZZ: Error: `since` value missing from data payload, and no previous since value exists
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at UserNotificationWatcher.addUser (/usr/bin/matrix-hookshot/Notifications/UserNotificationWatcher.js:69:19)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at LocalMQ.<anonymous> (/usr/bin/matrix-hookshot/Notifications/UserNotificationWatcher.js:31:18)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at LocalMQ.emit (node:events:518:28)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at LocalMQ.emit (node:domain:488:12)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at LocalMQ.push (/usr/bin/matrix-hookshot/MessageQueue/LocalMQ.js:31:14)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at Bridge.onAdminRoomSettingsChanged (/usr/bin/matrix-hookshot/Bridge.js:990:34)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at async /usr/bin/matrix-hookshot/Bridge.js:488:17
Jul 16 11:26:17 DietPi matrix-hookshot[798238]:     at async run (/usr/bin/matrix-hookshot/node_modules/p-queue/dist/index.js:163:29)

[sending the message a second time ...]

Jul 16 11:54:29 DietPi matrix-hookshot[798238]: /usr/bin/matrix-hookshot/Notifications/UserNotificationWatcher.js:69
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:             throw Error('`since` value missing from data payload, and no previous since value exists');
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:                   ^
Jul 16 11:54:29 DietPi matrix-hookshot[798238]: Error: `since` value missing from data payload, and no previous since value exists
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at UserNotificationWatcher.addUser (/usr/bin/matrix-hookshot/Notifications/UserNotificationWatcher.js:69:19)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at LocalMQ.<anonymous> (/usr/bin/matrix-hookshot/Notifications/UserNotificationWatcher.js:31:18)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at LocalMQ.emit (node:events:518:28)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at LocalMQ.emit (node:domain:488:12)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at LocalMQ.push (/usr/bin/matrix-hookshot/MessageQueue/LocalMQ.js:31:14)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at Bridge.onAdminRoomSettingsChanged (/usr/bin/matrix-hookshot/Bridge.js:990:34)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 16 11:54:29 DietPi matrix-hookshot[798238]: Node.js v20.12.2
Jul 16 11:54:29 DietPi systemd[1]: matrix-hookshot.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by dperdomo7** [comment]
I have the same issue, not sure why...
